controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

2fa_login:
  path: /2fa
  controller: App\Controller\SecurityController::check2fa

2fa_login_check:
  path: /2fa_check
